
export const EventName = {
    SETTING_BAR_EVENT: "SETTING_BAR_EVENT",
    CLIPART_BAR_OPEN_EVENT: "CLIPART_BAR_OPEN_EVENT",
    PRODUCT_PREVIEW_LOADED_EVENT: "PRODUCT_PREVIEW_LOADED_EVENT",
    PRODUCT_SELECT_MENU_MOUNTED_EVENT: "PRODUCT_SELECT_MENU_MOUNTED_EVENT",
};